package com.merker.common.util.app;

import org.apache.poi.hssf.usermodel.HSSFWorkbook;
import org.apache.poi.ss.usermodel.Row;
import org.apache.poi.ss.usermodel.Sheet;
import org.apache.poi.ss.usermodel.Workbook;
import org.junit.After;
import org.junit.Before;
import org.junit.Test;

import java.io.File;
import java.io.FileOutputStream;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Paths;

import static org.junit.Assert.assertTrue;

public class AppE2ETest {

    private File testDir;
    private File testFile;

    @Before
    public void setUp() throws IOException {
        testDir = Files.createTempDirectory("app_e2e_test").toFile();
        testFile = new File(testDir, "e2e_data.xls");

        try (Workbook workbook = new HSSFWorkbook()) {
            Sheet sheet = workbook.createSheet("E2ESheet");
            
            // Header Row
            Row header = sheet.createRow(0);
            header.createCell(0).setCellValue("System");
            header.createCell(1).setCellValue("Status");

            // Data Row
            Row data = sheet.createRow(1);
            data.createCell(0).setCellValue("Core");
            data.createCell(1).setCellValue("Online");

            try (FileOutputStream fileOut = new FileOutputStream(testFile)) {
                workbook.write(fileOut);
            }
        }
    }

    @After
    public void tearDown() {
        if (testDir != null && testDir.exists()) {
            File[] files = testDir.listFiles();
            if (files != null) {
                for (File file : files) {
                    file.delete();
                }
            }
            testDir.delete();
        }
    }

    @Test
    public void testAppMainE2EFlow() throws Exception {
        // Execute main method simulating command line call
        App.main(new String[]{testFile.getAbsolutePath()});

        // Verify that the files were generated correctly
        File expectedJsonFile = new File(testDir, "E2ESheet.json");
        File expectedTxtFile = new File(testDir, "E2ESheet.txt");

        assertTrue("JSON output file should be generated by the app flow", expectedJsonFile.exists());
        assertTrue("TXT output file should be generated by the app flow", expectedTxtFile.exists());

        String jsonContent = new String(Files.readAllBytes(Paths.get(expectedJsonFile.getAbsolutePath())));
        String txtContent = new String(Files.readAllBytes(Paths.get(expectedTxtFile.getAbsolutePath())));

        assertTrue("JSON should contain the processed data", jsonContent.contains("Core"));
        assertTrue("TXT should contain the processed data", txtContent.contains("Online"));
    }
}
